# Setup
version_name: mtmamba_plus_pascal
out_dir: "./"

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext
trBatch: 1
valBatch: 6
nworkers: 2
ignore_index: 255

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 1000
epochs: 99999
max_iter: 40000
optimizer: adamw
optimizer_kwargs:
   lr: 0.00008
   weight_decay: 0.000001
scheduler: poly

# Model
model: MTMamba_plus
backbone: swin_large

# Tasks
task_dictionary:
   include_semseg: True
   include_human_parts: True
   include_sal: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_scheme: log
   loss_weights:
       semseg: 1.0
       human_parts: 1.0
       sal: 1.0
       edge: 1.0
       normals: 1.0
