# Setup
version_name: mtmamba_plus_nyud
out_dir: "./"

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 1
valBatch: 6
nworkers: 2
ignore_index: 255

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 1000
epochs: 99999
max_iter: 40000
optimizer: adamw
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000001
scheduler: poly

# Model
model: MTMamba_plus
backbone: swin_large

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_scheme: none
   loss_weights:
       semseg: 1.0
       depth: 1.0
       normals: 10.0
       edge: 50.0
